version: "3.9"

services:
  rb-global-admin:
    container_name: rb-global-admin
    working_dir: /usr/app
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: rb-global-admin:latest
    ports:
      - "8080:8080"
    env_file:
     - ./.env
    # "Host port(edit for port conflict):container port"
    # networks:
    #   - caddy
# networks:
#   caddy:
#     external: true
# Use only if you need to reassign the network
