version: "3.9"

services:
  rb-global:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rb-global
    restart: unless-stopped
    ports:
      - 8000:8000
    volumes:
      - ./:/app
    networks:
      - caddy
networks:
  caddy:
    external: true
